import Undangan from "@/templates/Undangan/Undangan";
import { NextPage } from "next";
import Head from "next/head";

const Index: NextPage = () => {
    return (
        <>
            <Head>
                <title>serlydany</title>
                <meta name="description" content="Generated by Create Next Stack." />
            </Head>
            <Undangan />
        </>
    );
};

export default Index;
